/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 21-апр.-2021 14:35:46 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `content` CASCADE
;

/* Create Tables */

CREATE TABLE `content`
(
	`c_id` BIGINT NOT NULL,
	`ct_id` INT NOT NULL,
	`c_name` VARCHAR(250) NOT NULL,
	`c_release_date` DATETIME NULL,
	`c_text_description` VARCHAR(300) NULL,
	`c_duration` TIME NOT NULL,
	`ch_id` BIGINT NULL,
	CONSTRAINT `PK_content` PRIMARY KEY (`c_id` ASC, `ct_id` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `content` 
 ADD INDEX `IXFK_content_content_types` (`ct_id` ASC)
;

ALTER TABLE `content` 
 ADD INDEX `IXFK_content_copyrigth_holders` (`ch_id` ASC)
;

ALTER TABLE `content` 
 ADD INDEX `IDX_content_release_date` (`c_release_date` ASC)
;

ALTER TABLE `content` 
 ADD INDEX `IDX_content_name_content_type_id` (`ct_id` ASC, `c_name` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `content` 
 ADD CONSTRAINT `FK_content_content_types`
	FOREIGN KEY (`ct_id`) REFERENCES `content_types` (`ct_id`) ON DELETE No Action ON UPDATE Cascade
;

ALTER TABLE `content` 
 ADD CONSTRAINT `FK_content_copyrigth_holders`
	FOREIGN KEY (`ch_id`) REFERENCES `copyrigth_holders` (`ch_id`) ON DELETE No Action ON UPDATE Cascade
;

SET FOREIGN_KEY_CHECKS=1
; 
