/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 21-апр.-2021 14:52:48 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `profiles` CASCADE
;

/* Create Tables */

CREATE TABLE `profiles`
(
	`p_id` BIGINT NOT NULL,
	`u_id` BIGINT NULL,
	`pt_id` INT NULL,
	`p_name` VARCHAR(310) NOT NULL,
	`p_surname` VARCHAR(310) NULL,
	`profiles_is_active` BIT NULL,
	CONSTRAINT `PK_profiles` PRIMARY KEY (`p_id` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `profiles` 
 ADD INDEX `IXFK_profiles_profile_types` (`pt_id` ASC)
;

ALTER TABLE `profiles` 
 ADD INDEX `IXFK_profiles_users` (`u_id` ASC)
;

ALTER TABLE `profiles` 
 ADD INDEX `IDX_users_id_profiles_is_active` (`u_id` ASC, `profiles_is_active` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `profiles` 
 ADD CONSTRAINT `FK_profiles_profile_types`
	FOREIGN KEY (`pt_id`) REFERENCES `profile_types` (`pt_id`) ON DELETE No Action ON UPDATE Cascade
;

ALTER TABLE `profiles` 
 ADD CONSTRAINT `FK_profiles_users`
	FOREIGN KEY (`u_id`) REFERENCES `user` (`u_id`) ON DELETE Cascade ON UPDATE Cascade
;

SET FOREIGN_KEY_CHECKS=1
; 
