/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 25-апр.-2021 21:42:51 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `users` CASCADE
;

/* Create Tables */

CREATE TABLE `users`
(
	`u_id` BIGINT NOT NULL,
	`u_email` VARCHAR(320) NOT NULL,
	`u_password` VARCHAR(50) NOT NULL,
	`u_is_active` BIT NOT NULL,
	`u_last_payment_date` DATETIME NOT NULL,
	`u_is_auto_payment` BIT NOT NULL,
	`ust_id` TINYINT NULL,
	CONSTRAINT `PK_users` PRIMARY KEY (`u_id` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `users` 
 ADD INDEX `IXFK_users_user_sybscription_types` (`ust_id` ASC)
;

ALTER TABLE `users` 
 ADD INDEX `IDX_users_email_users_password` (`u_email` ASC, `u_password` ASC)
;

ALTER TABLE `users` 
 ADD INDEX `IDX_users_last_payment_date_user_is_auto_paymeny` (`u_last_payment_date` ASC, `u_is_auto_payment` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `users` 
 ADD CONSTRAINT `FK_users_user_sybscription_types`
	FOREIGN KEY (`ust_id`) REFERENCES `user_subscription_types` (`ust_id`) ON DELETE No Action ON UPDATE Cascade
;

SET FOREIGN_KEY_CHECKS=1
; 
